// src/lib/components/Board.svelte
<script>
	const boardLines = [
		{ x1: '100', y1: '300', x2: '900', y2: '300' },
		{ x1: '100', y1: '500', x2: '900', y2: '500' },
		{ x1: '100', y1: '700', x2: '900', y2: '700' },
		{ x1: '100', y1: '900', x2: '900', y2: '900' },
		{ x1: '100', y1: '1100', x2: '900', y2: '1100' },
		{ x1: '100', y1: '1100', x2: '100', y2: '300' },
		{ x1: '300', y1: '1100', x2: '300', y2: '300' },
		{ x1: '500', y1: '1300', x2: '500', y2: '100' },
		{ x1: '700', y1: '1100', x2: '700', y2: '300' },
		{ x1: '900', y1: '1100', x2: '900', y2: '300' },
		{ x1: '100', y1: '700', x2: '700', y2: '1300' },
		{ x1: '900', y1: '700', x2: '300', y2: '1300' },
		{ x1: '100', y1: '700', x2: '700', y2: '100' },
		{ x1: '900', y1: '700', x2: '300', y2: '100' },
		{ x1: '300', y1: '100', x2: '700', y2: '100' },
		{ x1: '300', y1: '1300', x2: '700', y2: '1300' },
		{ x1: '400', y1: '200', x2: '600', y2: '200' },
		{ x1: '400', y1: '1200', x2: '600', y2: '1200' },
		{ x1: '100', y1: '300', x2: '900', y2: '1100' },
		{ x1: '900', y1: '300', x2: '100', y2: '1100' }
	];
	const boardCoordinate = [
		{ x: '100', y: '300' },
		{ x: '100', y: '500' },
		{ x: '300', y: '500' },
		{ x: '500', y: '500' },
		{ x: '700', y: '500' },
		{ x: '100', y: '700' },
		{ x: '300', y: '700' },
		{ x: '500', y: '700' },
		{ x: '700', y: '700' },
		{ x: '100', y: '900' },
		{ x: '300', y: '900' },
		{ x: '500', y: '900' },
		{ x: '700', y: '900' },
		{ x: '100', y: '1100' },
		{ x: '100', y: '1100' },
		{ x: '300', y: '1100' },
		{ x: '500', y: '1100' },
		{ x: '500', y: '1300' },
		{ x: '700', y: '1100' },
		{ x: '300', y: '100' },
		{ x: '300', y: '1300' },
		{ x: '400', y: '200' },
		{ x: '400', y: '1200' },
		{ x: '900', y: '500' },
		{ x: '900', y: '700' },
		{ x: '900', y: '900' },
		{ x: '300', y: '300' },
		{ x: '500', y: '300' },
		{ x: '500', y: '100' },
		{ x: '700', y: '300' },
		{ x: '900', y: '300' },
		{ x: '700', y: '1300' },
		{ x: '300', y: '1300' },
		{ x: '700', y: '100' },
		{ x: '300', y: '100' },
		{ x: '700', y: '100' },
		{ x: '700', y: '1300' },
		{ x: '600', y: '200' },
		{ x: '600', y: '1200' },
		{ x: '900', y: '1100' },
		{ x: '100', y: '1100' }
	];
</script>

{#each boardLines as line}
	<line
		x1={line.x1}
		y1={line.y1}
		x2={line.x2}
		y2={line.y2}
		stroke="#525252"
		stroke-linecap="round"
		stroke-dasharray="6 6"
	/>
{/each}
{#each boardCoordinate as coordinate}
	<text x={coordinate.x} y={coordinate.y} class="text-gray-500 text-sm fill-current">
		[{coordinate.x},{coordinate.y}]
	</text>
{/each}

// app/components/Board.vue
<script setup lang="ts">
const store = useGameStore();
const appConfig = useAppConfig();
</script>

<template>
  <line
    v-for="line in boardLines"
    :x1="line.x1"
    :y1="line.y1"
    :x2="line.x2"
    :y2="line.y2"
    stroke="currentColor"
    :stroke-width="3"
    stroke-linecap="round"
    stroke-dasharray="6 6"
    class="text-white/50"
  />

  <text
    v-if="appConfig.debug"
    v-for="coordinate in boardCoordinate"
    :key="`${coordinate.x},${coordinate.y}`"
    :x="coordinate.x + 40"
    :y="coordinate.y + 20"
    class="fill-current text-base text-white"
  >
    [{{ coordinate.x }},{{ coordinate.y }}]
  </text>

  <line
    v-for="line in store.dam.coordinates"
    :key="`${line.activePawn.x},${line.activePawn.y}`"
    :x1="line.activePawn.x"
    :y1="line.activePawn.y"
    :x2="line.target.x"
    :y2="line.target.y"
    class="stroke-current"
    :stroke-width="64"
    stroke-linecap="round"
  />
</template>
