// src/lib/components/SuggestionPawn.svelte
<script lang="ts">
	import { activePawn } from '$lib/store/state';
	import { fade } from 'svelte/transition';
	import { Color, type Coordinate } from '$lib/types/global.type';
	import { createEventDispatcher } from 'svelte';

	const dispatch = createEventDispatcher();

	export let coordinate: Coordinate;
</script>

<circle
	on:click={() => dispatch('click', coordinate)}
	cx={coordinate.x}
	cy={coordinate.y}
	fill="#000"
	opacity="0"
	r="64"
	class="cursor-pointer highlight-none"
/>

<circle
	cx={coordinate.x}
	cy={coordinate.y}
	r="40"
	class="cursor-pointer highlight-none pointer-events-none fill-current 
	{$activePawn.color === Color.RED ? 'text-red-400' : 'text-blue-400'}"
	stroke="#fff"
	opacity="0.7"
	stroke-width="12"
	transition:fade={{ duration: 150 }}
/>

<style>
	.highlight-none {
		-webkit-tap-highlight-color: transparent;
	}
</style>

// app/components/SuggestionPawn.vue
<script setup lang="ts">
import type { Coordinate } from "~/types/global";

const props = defineProps<{
  coordinate: Coordinate;
}>();

const store = useGameStore();
</script>

<template>
  <circle
    :cx="coordinate.x"
    :cy="coordinate.y"
    fill="#000"
    opacity="0"
    :r="64"
    class="highlight-none cursor-pointer"
  />

  <circle
    :cx="coordinate.x"
    :cy="coordinate.y"
    :r="40"
    class="highlight-none pointer-events-none cursor-pointer fill-current"
    :class="
      store.activePawn?.color === 'red' ? 'text-red-400' : 'text-blue-400'
    "
    stroke="#fff"
    opacity="0.7"
    stroke-width="12"
  />
</template>

<style scoped>
.highlight-none {
  -webkit-tap-highlight-color: transparent;
}
</style>
