// app/components/Pawn.vue
<script setup lang="ts">
import { useGameStore } from "~/stores/game";
import type { Pawn } from "~/types/global";

const store = useGameStore();

const props = defineProps<{
  pawn: Pawn;
  isActive: boolean;
}>();

const emit = defineEmits<{
  (e: "click", pawn: Pawn): void;
  (e: "removePawn", pawn: Pawn): void;
}>();

function onClick() {
  if (store.dam.coordinates.length > 0) {
    if (
      store.dam.coordinates.some(
        (pawn) =>
          pawn.activePawn.x === props.pawn.x &&
          pawn.activePawn.y === props.pawn.y,
      )
    ) {
      emit("removePawn", props.pawn);
    }
    return;
  }

  emit("click", props.pawn);
}
</script>

<template>
  <circle
    :cx="pawn.x"
    :cy="pawn.y"
    fill="#000"
    :opacity="0"
    r="64"
    class="highlight-none cursor-pointer"
  />

  <circle
    :cx="pawn.x"
    :cy="pawn.y"
    r="40"
    class="highlight-none cursor-pointer"
    :class="{ 'pointer-events-none': pawn.color !== store.turn }"
    :fill="pawn.color === 'red' ? '#FF005C' : '#426AF5'"
    stroke="#fff"
    stroke-width="12"
    transition:fade={{ duration: 400, easing: cubicOut }}
  />
</template>

<style scoped>
.highlight-none {
  -webkit-tap-highlight-color: transparent;
}
</style>

// src/lib/components/Pawn.svelte
<script lang="ts">
	import { dam, turn } from '$lib/store/state';
	import { Color, type Pawn } from '$lib/types/global.type';
	import { createEventDispatcher } from 'svelte';
	import { fade } from 'svelte/transition';
	import { cubicOut, quintOut } from 'svelte/easing';
	import { tweened } from 'svelte/motion';

	export let pawn: Pawn;
	export let isActive: boolean = false;

	const dispatch = createEventDispatcher();

	const tweenedX = tweened(pawn.x, { duration: 400, easing: cubicOut });
	const tweenedY = tweened(pawn.y, { duration: 400, easing: cubicOut });
	const tweenedR = tweened(40, { duration: 300, easing: quintOut, delay: 0 });

	$: {
		tweenedX.set(pawn.x);
		tweenedY.set(pawn.y);
		isActive ? tweenedR.set(54) : tweenedR.set(40);
	}

	function onClick() {
		if ($dam.color === pawn.color) {
			dispatch('removePawn', pawn);
			return;
		}
		dispatch('click', pawn);
	}
</script>

<circle
	on:click={onClick}
	cx={pawn.x}
	cy={pawn.y}
	fill="#000"
	opacity="0"
	r="64"
	class="cursor-pointer highlight-none"
/>

<circle
	cx={$tweenedX}
	cy={$tweenedY}
	r={$tweenedR}
	class="pointer-events-none fill-current {pawn.color === Color.RED ? 'text-red-500' : 'text-blue-600'}"
	class:pointer-event-none={pawn.color !== $turn}
	fill={pawn.color === Color.RED ? '#FF005C' : '#426AF5'}
	stroke="#fff"
	stroke-width="12"
	transition:fade={{ duration: 400, easing: cubicOut }}
/>

<style>
	.highlight-none {
		-webkit-tap-highlight-color: transparent;
	}
</style>
